// Balloon Hangman word library
// 기준: 미국 영어, 5~9글자, 쉬운 일상 단어, 힌트 없음.
// word는 반드시 A-Z 대문자만 사용합니다.

window.WORD_LIBRARY = [
  { word: "APPLE", meaning: "사과" },
  { word: "WATER", meaning: "물" },
  { word: "MUSIC", meaning: "음악" },
  { word: "HAPPY", meaning: "행복한" },
  { word: "COLOR", meaning: "색깔" },
  { word: "OCEAN", meaning: "바다" },
  { word: "RIVER", meaning: "강" },
  { word: "BEACH", meaning: "해변" },
  { word: "CLOUD", meaning: "구름" },
  { word: "SUNNY", meaning: "화창한" },
  { word: "ROBOT", meaning: "로봇" },
  { word: "SCHOOL", meaning: "학교" },
  { word: "FRIEND", meaning: "친구" },
  { word: "ANIMAL", meaning: "동물" },
  { word: "WINDOW", meaning: "창문" },
  { word: "DINNER", meaning: "저녁 식사" },
  { word: "COOKIE", meaning: "쿠키" },
  { word: "PENCIL", meaning: "연필" },
  { word: "CAMERA", meaning: "카메라" },
  { word: "FLOWER", meaning: "꽃" },
  { word: "GARDEN", meaning: "정원" },
  { word: "ORANGE", meaning: "오렌지" },
  { word: "BANANA", meaning: "바나나" },
  { word: "MARKET", meaning: "시장" },
  { word: "FAMILY", meaning: "가족" },
  { word: "BUTTER", meaning: "버터" },
  { word: "CHEESE", meaning: "치즈" },
  { word: "TURTLE", meaning: "거북" },
  { word: "RABBIT", meaning: "토끼" },
  { word: "MONKEY", meaning: "원숭이" },
  { word: "CENTER", meaning: "중심, 센터" },
  { word: "TRAVEL", meaning: "여행하다" },
  { word: "CANDLE", meaning: "양초" },
  { word: "PILLOW", meaning: "베개" },
  { word: "BOTTLE", meaning: "병" },
  { word: "POCKET", meaning: "주머니" },
  { word: "WALLET", meaning: "지갑" },
  { word: "PLANET", meaning: "행성" },
  { word: "FOREST", meaning: "숲" },
  { word: "BRIDGE", meaning: "다리" },
  { word: "CASTLE", meaning: "성" },
  { word: "DRAGON", meaning: "용" },
  { word: "ROCKET", meaning: "로켓" },
  { word: "DESERT", meaning: "사막" },
  { word: "ISLAND", meaning: "섬" },
  { word: "WINTER", meaning: "겨울" },
  { word: "SUMMER", meaning: "여름" },
  { word: "SPRING", meaning: "봄" },
  { word: "AUTUMN", meaning: "가을" },
  { word: "CIRCLE", meaning: "원" },
  { word: "SQUARE", meaning: "정사각형" },
  { word: "NUMBER", meaning: "숫자" },
  { word: "LETTER", meaning: "글자, 편지" },
  { word: "SPIDER", meaning: "거미" },
  { word: "TURKEY", meaning: "칠면조" },
  { word: "PIRATE", meaning: "해적" },
  { word: "COWBOY", meaning: "카우보이" },
  { word: "DOCTOR", meaning: "의사" },
  { word: "FARMER", meaning: "농부" },
  { word: "SINGER", meaning: "가수" },
  { word: "DRIVER", meaning: "운전사" },
  { word: "CARROT", meaning: "당근" },
  { word: "POTATO", meaning: "감자" },
  { word: "TOMATO", meaning: "토마토" },
  { word: "MORNING", meaning: "아침" },
  { word: "PICTURE", meaning: "그림, 사진" },
  { word: "BALLOON", meaning: "풍선" },
  { word: "LIBRARY", meaning: "도서관" },
  { word: "RAINBOW", meaning: "무지개" },
  { word: "CHICKEN", meaning: "닭, 치킨" },
  { word: "KITCHEN", meaning: "부엌" },
  { word: "BEDROOM", meaning: "침실" },
  { word: "WEATHER", meaning: "날씨" },
  { word: "HOLIDAY", meaning: "휴일" },
  { word: "AIRPORT", meaning: "공항" },
  { word: "PRESENT", meaning: "선물" },
  { word: "THEATER", meaning: "극장" },
  { word: "VOLCANO", meaning: "화산" },
  { word: "BICYCLE", meaning: "자전거" },
  { word: "LANTERN", meaning: "랜턴" },
  { word: "GIRAFFE", meaning: "기린" },
  { word: "PENGUIN", meaning: "펭귄" },
  { word: "DOLPHIN", meaning: "돌고래" },
  { word: "OCTOPUS", meaning: "문어" },
  { word: "PANCAKE", meaning: "팬케이크" },
  { word: "CUPCAKE", meaning: "컵케이크" },
  { word: "POPCORN", meaning: "팝콘" },
  { word: "PUMPKIN", meaning: "호박" },
  { word: "LETTUCE", meaning: "상추" },
  { word: "CABBAGE", meaning: "양배추" },
  { word: "COMPUTER", meaning: "컴퓨터" },
  { word: "ELEPHANT", meaning: "코끼리" },
  { word: "MOUNTAIN", meaning: "산" },
  { word: "BIRTHDAY", meaning: "생일" },
  { word: "NOTEBOOK", meaning: "공책" },
  { word: "BASEBALL", meaning: "야구" },
  { word: "SANDWICH", meaning: "샌드위치" },
  { word: "UMBRELLA", meaning: "우산" },
  { word: "BACKPACK", meaning: "배낭" },
  { word: "CALENDAR", meaning: "달력" },
  { word: "HOSPITAL", meaning: "병원" },
  { word: "QUESTION", meaning: "질문" },
  { word: "FIREWORK", meaning: "불꽃" },
  { word: "KANGAROO", meaning: "캥거루" },
  { word: "DINOSAUR", meaning: "공룡" },
  { word: "EXERCISE", meaning: "운동" },
  { word: "FAVORITE", meaning: "가장 좋아하는" },
  { word: "TREASURE", meaning: "보물" },
  { word: "BUTTERFLY", meaning: "나비" },
  { word: "CHOCOLATE", meaning: "초콜릿" },
  { word: "BREAKFAST", meaning: "아침 식사" },
  { word: "ALLIGATOR", meaning: "악어" },
  { word: "HAMBURGER", meaning: "햄버거" },
  { word: "BLUEBERRY", meaning: "블루베리" },
  { word: "PINEAPPLE", meaning: "파인애플" }
];
